services:
  - type: web
    name: clip-search-app
    env: python
    buildCommand: ""
    startCommand: python flask/app.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp_key.json
    plan: free
    region: oregon
