services:
  - type: web
    name: flask_fashion
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp_key.json
    secretFiles:
      - name: gcp_key.json
        mountPath: /etc/secrets/gcp_key.json
    rootDir: .
